const mongoose = require("mongoose");
const AutoIncrement = require("mongoose-sequence")(mongoose);

const Schema = mongoose.Schema;

const pabSchema = new Schema(
  {
    id: { type: Number },
    RID: { type: String, required: true, unique: true },
    firstName_KH: { type: String, required: true },
    lastName_KH: { type: String },
    otherName_KH: { type: String },
    firstName_EN: { type: String, required: true },
    lastName_EN: { type: String },
    otherName_EN: { type: String },
    otherNameSource: { type: String },
    nameSourceNotes: { type: String },
    gender: { type: String, required: true },
    genderSource: { type: String },
    age: { type: Number, required: true },
    Height: { type: String },
    Body: { type: String },

    nationality_KH: { type: String, required: true },
    socialStatus_KH: { type: String },
    physicalCharacterstics_KH: { type: String },
    dateOfBirthNote_KH: { type: String },
    nationality_EN: { type: String, required: true },
    socialStatus_EN: { type: String },
    physicalCharacterstics_EN: { type: String },
    dateOfBirthNote_EN: { type: String },
    nationlaitySource: { type: String, required: true },
    socialStatusSource: { type: String },
    physicalCharactersticsSource: { type: String },
    dateOfBirthNoteSource: { type: String },

    birthPlaceCity: { type: String, required: true },
    birthPlaceDistrict: { type: String, required: true },
    birthPlaceCommune: { type: String, required: true },
    birthPlaceSrok: { type: String },
    birthPlaceDamban: { type: String },
    birthPlaceNoteSource: { type: String },
    deathDate: { type: Date, required: true },
    deathDateNote_KH: { type: String },
    deathDateNote_EN: { type: String },

    deathPlaceCity: { type: String, required: true },
    deathPlaceDistrict: { type: String, required: true },
    deathPlaceCommune: { type: String, required: true },
    deathPlaceSource: { type: String },
    deathPlaceKhum_KH: { type: String, required: true },
    deathPlacePhum_KH: { type: String, required: true },
    deathPlaceNote_KH: { type: String },
    deathPlaceKhum_EN: { type: String, required: true },
    deathPlacePhum_EN: { type: String, required: true },
    deathPlaceNote_EN: { type: String },

    fatherName_KH: { type: String, required: true },
    fatherOccupation_KH: { type: String, required: true },
    fatherAge: { type: Number },
    fatherAgeNote_KH: { type: String },
    fatherName_EN: { type: String, required: true },
    fatherOccupation_EN: { type: String, required: true },
    fatherAgeSource: { type: String },
    fatherAgeNote_EN: { type: String },

    motherName_KH: { type: String, required: true },
    motherOccupation_KH: { type: String, required: true },
    motherAge: { type: Number },
    motherAgeNote_KH: { type: String },
    motherName_EN: { type: String, required: true },
    motherOccupation_EN: { type: String, required: true },
    motherAgeSource: { type: String },
    motherAgeNote_EN: { type: String },

    preDkEducation_KH: { type: String, required: true },
    preDkEducation_EN: { type: String, required: true },
    preDkEducationSource: { type: String },
    preDkOccupation_KH: { type: String },
    presDkOccupation_EN: { type: String },
    presDkNote_KH: { type: String },
    presDkNote_EN: { type: String },
    presDkNoteSource: { type: String },

    KR_Rank_pre75_KH: { type: String },
    KR_Rank_pre75_EN: { type: String },
    KR_Rank_pre75_Source: { type: String },

    DKZone_75_79_KH: { type: String },
    DKOrgType_75_79_KH: { type: String },
    DKOrgUnit_75_79_KH: { type: String },
    DKZone_75_79_EN: { type: String },
    DKOrgType_75_79_EN: { type: String },
    DKOrgUnit_75_79_EN: { type: String },
    DKZone_75_79_Source: { type: String },
    DKOrgType_75_79_Source: { type: String },
    DKOrgUnit_75_79_Source: { type: String },

    KR_Rank_75_79_KH: { type: String },
    KR_Rank_75_79_EN: { type: String },
    KR_Rank_75_79_Source: { type: String },

    KR_Rank_Post_79_KH: { type: String },
    KR_Rank_Post_79_EN: { type: String },
    KR_Rank_Post_79_Source: { type: String },

    subordinates_KH: { type: String },
    subordinates_EN: { type: String },
    subordinates_Source: { type: String },

    persecutor_KH: { type: String },
    persecutorBy_KH: { type: String },
    detentionPlace_KH: { type: String },
    persecutor_EN: { type: String },
    persecutorBy_EN: { type: String },
    detentionPlace_EN: { type: String },
    persecutorBySource: { type: String },

    arrestDate: { type: Date },
    arrestSource: { type: String },
    arrestPlace_KH: { type: String },
    arrestPlace_EN: { type: String },
    arrestReason_KH: { type: String },
    arrestReason_EN: { type: String },

    prison_History_KH: { type: String },
    international_Instruments_KH: { type: String },
    dateExecution_KH: { type: Date },
    prison_History_EN: { type: String },
    international_Instruments_EN: { type: String },
    prison_HistorySource: { type: String },
    international_Instruments_Source: { type: String },
    dateExecution_Source: { type: String },
    indexTerm_KH: { type: String },
    codeEnter_KH: { type: String },
    linkingFields_NonText_KH: { type: String },
    indexTerm_EN: { type: String },
    codeEnter_EN: { type: String },
    linkingFields_NonText_EN: { type: String },
    indexTerm_Source: { type: String },
    codeEnter_Source: { type: String },
    linkingFields_NonText_Source: { type: String },
    otherLink_KH: { type: String },
    otherLink_EN: { type: String },
    otherLink_Source: { type: String },

    activity_source: { type: String },
    khmer_Activity: { type: String },
    english_Activity: { type: String },

    associate_Source: { type: String },
    khmer_Associate: { type: String },
    english_Associate: { type: String },

    party_Source: { type: String },
    khmer_Party: { type: String },
    english_Party: { type: String },

    relation_Source: { type: String },
    khmer_Relation: { type: String },
    english_Relation: { type: String },

    resistance_Source: { type: String },
    khmer_Resistance: { type: String },
    english_Resistance: { type: String },

    superior_Source: { type: String },
    khmer_Superior: { type: String },
    english_Superior: { type: String },

    copyright_KH: { type: String },
    copyright_EN: { type: String },
    publish: { type: String },
  },

  {
    timestamps: true,
  }
);

pabSchema.plugin(AutoIncrement, { inc_field: "id", id: "pabId" });
module.exports = mongoose.model("pab", pabSchema);
